#!/bin/bash

# Define the compose file to use.
COMPOSE="docker-compose -f docker-compose.yml"


# Run php artisan command in the php container
function artisan()
{   
    shift
    $COMPOSE run --rm $TTY \
        -w /var/www/html \
        php \
        php artisan "$@"

    exit
}


# Run composer command in the php container.
function composer()
{
    shift
    $COMPOSE run --rm $TTY \
        -u www-data \
        -w /var/www/html \
        php \
        composer $@

    exit
}


# Run phpunit command in the php container.
function test()
{
    if [[ $1 == "test" ]]; then
        shift
        $COMPOSE run --rm $TTY \
            -w /var/www/html \
            php \
            ./vendor/bin/phpunit $@
    else
        # Run phpunit command in the php container already running.
        shift
        $COMPOSE exec \
        php \
        sh -c "cd /var/www/html && ./vendor/bin/phpunit $@"
    fi
    exit
}


# Install laravel relative to the containers work directory. 
function install_laravel()
{
    shift
    $COMPOSE run --rm $TTY \
        -w /var/www/html \
        -u www-data \
        php \
        composer create-project --prefer-dist laravel/laravel $@
    
    $COMPOSE rm -f applications
    exit
}


# Simply prints out the commands available to run.
function usage()
{
    echo "Usage: ./dockit [command]"
    echo
    echo "Commands:"
    echo "  art        Run php artisan in the php container"
    echo "  composer   Run composer in the php container"
    echo "  test|t     Run phpunit php container. Running t requires an already running container, but is faster."
    echo
    echo "  To run any docker-compose command just use ./dockit <command> i.e ./dockit ps"
}

# Catch the command and run it.
case $1 in
    (art)   
        artisan $@
        ;;
    (composer)   
        composer $@
        ;;
    (install-laravel)   
        install_laravel $@
        ;;
    (test|t)   
        test $@
        ;;
    (-h | --help | "")
        usage
        exit
        ;;
    (*)   
        $COMPOSE $@
        exit
        ;;
esac