version: '3.2'

services:
  php:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - INSTALL_PHPREDIS=${PHP_INSTALL_PHPREDIS}
    image: justdockit-laravel/php
    volumes: &base_volume
      - type: volume
        source: "${APP_PATH}"
        target: /var/www/html
      - ~/.composer/cache:/.composer/cache 

  nginx:
    build:
      context: ./docker/nginx
    image: justdockit-laravel/nginx
    volumes: *base_volume
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php

  node:
    build:
      context: ./docker/node
    image: justdockit-laravel/node
    volumes: *base_volume

  mariadb:
    build:
      context: ./docker/mariadb
    image: justdockit-laravel/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
      MYSQL_USER: "${MARIADB_USER}"
      MYSQL_PASSWORD: "${MARIADB_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: "mariadb"
      PMA_USER: "root"
      PMA_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    ports:
      - "${PMA_PORT}:80"
    volumes:
      - pma_session:/sessions
  
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
  pma_session:
